<?php
$vars = array(
    'productCount' => $woocommerce->cart->get_cart_contents_count()
);

if (isset($additionaClass) && $additionaClass == 'festi-cart-widget') {
    echo $this->fetch('show_or_hide_widget.phtml', $vars);
}

$hideCart = (array_key_exists('hideCart', $settings) && !$vars['productCount']) ? 'display: none' : 'display: inline-block';


$classForEvent = (wp_is_mobile() || $settings['dropdownAction'] == 'disable') ? '' : $settings['dropdownAction'];
?>


<a id="festi-cart" 
    style = "<?php echo $hideCart; ?>"
    class="
        festi-cart
        <?php if (isset($additionaClass) && ($additionaClass!='festi-cart-menu' || array_key_exists('customizeCartInMenu', $settings))) echo 'festi-cart-customize'; ?>  
        <?php if (isset($additionaClass)) echo $additionaClass; ?>  
        festi-cart-<?php echo $classForEvent; ?> 
    "
    href="<?php echo $woocommerce->cart->get_cart_url();?>"
>
    <?php
    if (isset($additionaClass)) {
       $vars['additionaClass'] = $additionaClass;
    }
    
    $vars['woocommerce'] = $woocommerce;
    $vars['settings'] = $settings;
     
    echo $this->fetch('cart_content.phtml', $vars); 
     ?>
</a>