<hr width="100%" style="border: 4px dashed #A1AFED" color="#FFFFFF" size="6">
<p>This plugin for WooCommerce Payment Gateway per Product lets you select the available payment method for each individual product. This plugin will allow the admin to select the available payment gateway for each individual product. Admin can select for each individual product the payment gateway that will be used by checkout. If no selection is made, then the default payment gateways are displayed. If you for example only select paypal then only paypal will available for that product by checking out.</p>
<p>
This version is for small shops with maximal <b>2 categories<b>.<br>For a really small fee of 19,95 you can get the Premium version with <a href="https://www.dreamfoxmedia.com/shop/plugins/woocommerce-payment-gateway-per-product-premium#utm_source=plugin&utm_medium=unlimited_cats&utm_campaign=dfm-wcpgpp-f" target="_new">Unlimited Categories</a>
<hr width="100%" style="border: 4px dashed #A1AFED" color="#FFFFFF" size="6">
</p>
