<hr width="100%" style="border: 4px dashed #A1AFED" color="#FFFFFF" size="6">
<img src="<?php echo $pluginurl ?>../images/donation.png" alt="help-button">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <center>Like this product we’ve made and want to contribute to its future development? Donate however much you’d like with the below donate button<br>    
    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="UNTLWQSLRH85U">
    <input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="<?php echo __('PayPal – The safer, easier way to pay online.') ?>">
</center>
</form>
<hr width="100%" style="border: 4px dashed #A1AFED" color="#FFFFFF" size="6">