<hr width="100%" style="border: 4px dashed #A1AFED" color="#FFFFFF" size="6">
<img src="<?php echo $pluginurl ?>../images/Need-Help.png" alt="help-button"
	<?php echo __('<br><br>Below you will find the top 5 questions in our FAQ. Maybe they can help you in the right direction.	
	<ul class="ul-square">
                    <li><a href="https://www.dreamfoxmedia.com/ufaqs/plugin-not-working#utm_source=plugin&utm_medium=faq_link&utm_campaign=dfm-wcpgpp-f" target="_blank">The plugin is not working.</a></li>
                    <li><a href="https://www.dreamfoxmedia.com/ufaqs/can-select-2-categories#utm_source=plugin&utm_medium=faq_link&utm_campaign=dfm-wcpgpp-f" target="_blank">I can only select 2 categories</a></li>
                    <li><a href="https://www.dreamfoxmedia.com/ufaqs/can-set-different-payments-methods#utm_source=plugin&utm_medium=faq_link&utm_campaign=dfm-wcpgpp-f" target="_blank">Where can I set different payments methods?</a></li>
                    <li><a href="https://www.dreamfoxmedia.com/ufaqs/video-instructions#utm_source=plugin&utm_medium=faq_link&utm_campaign=dfm-wcpgpp-f" target="_blank">Video Instructions</a></li>
                    <li><a href="https://www.dreamfoxmedia.com/kb-woocommerce-payment-gateway-per-product#utm_source=plugin&utm_medium=faq_link&utm_campaign=dfm-wcpgpp-f" target="_blank">See here the complete FAQ</a></li>
				         </ul><br>');
      ?><?php echo sprintf(__('If your answer can not be found in the resources listed above, please use our support form on <a href="%s" target="_blank">dreamfoxmedia.com</a>.'), 'https://www.dreamfoxmedia.com/support-request-free-plugins/'); ?></p>
	</p>
