<div class="wcpgpp-box" >
    <h4 class="wcpgpp-title"><?php echo __('Looking for help?', 'woocommerce paypent per product'); ?></h4>
    <p><?php echo __('We have some resources available to help you in the right direction.', 'woocommerce paypent per product'); ?></p>
    <ul class="ul-square">
        <li><a href="http://www.dreamfoxmedia.com/ufaq-category/wcpgpp-f/#utm_source=plugin&utm_medium=faq&utm_campaign=wcpgpp"><?php echo __('Knowledge Base', 'woocommerce paypent per product'); ?></a></li>
        <li><a href="https://wordpress.org/plugins/woocommerce-product-payments/faq/"><?php echo __('Frequently Asked Questions', 'woocommerce paypent per product'); ?></a></li>
    </ul>
    <p><?php echo sprintf(__('If your answer can not be found in the resources listed above, please use the <a href="%s">support forums on WordPress.org</a>.'), 'https://wordpress.org/support/plugin/woocommerce-product-payments'); ?></p>
    <p><?php echo sprintf(__('Found a bug? Please <a href="%s">open an issue on GitHub</a>.'), 'https://github.com/dreamfoxnl/WC-Payment-Gateway-per-Product-Free/issues'); ?></p>
</div>