<hr width="100%" style="border: 4px dashed #A1AFED" color="#FFFFFF" size="6">
<img src="<?php echo $pluginurl ?>../images/newsletter-button.png" alt="<?php echo $pluginurl ?> newsletter-button">
<!-- start: mailjet Signup Form HTML Code -->
<br><br>
<data data-token="c5a707574163f47bcaebd945f5341653" class="mj-w-data" data-apikey="30TI" data-w-id="auM" data-lang="en_US" data-base="https://app.mailjet.com" data-width="640" data-height="410" data-statics="statics"></data>
<div class="mj-w-button mj-w-btn" data-token="c5a707574163f47bcaebd945f5341653" style="font-family: Ubuntu, Helvetica; color: white; padding: 0 25px; background-color: #336699; text-align: center; vertical-align: middle; display: inline-block; border-radius: 3px;">
    <div style="display: table; height: 45px;">
        <div style="display: table-cell; vertical-align: middle;">
            <div class="mj-w-button-content" style="font-family:Ubuntu, Helvetica; display: inline-block; text-align: center; font-size: 13px; vertical-align: middle;"><b>SUBSCRIBE TO NEWSLETTER!</b></div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://app.mailjet.com/statics/js/widget.modal.js"></script>
<br><br>
<!-- end: mailjet Signup Form HTML Code -->